-- 1. departments (부서)
INSERT INTO departments (name, description, established_date) VALUES
                                                                  ('경영지원팀', '인사, 회계 및 총무 업무를 담당합니다.', '2020-01-01'),
                                                                  ('기술개발팀', '플랫폼 서비스의 설계 및 개발을 담당합니다.', '2020-01-01'),
                                                                  ('디자인팀', 'UI/UX 및 브랜드 디자인을 담당합니다.', '2021-03-15'),
                                                                  ('디자인2팀', 'UI/UX 및 브랜드 디자인을 담당합니다.', '2021-03-15'),
                                                                  ('디자인3팀', 'UI/UX 및 브랜드 디자인을 담당합니다.', '2021-03-15'),
                                                                  ('마케팅팀', '콘텐츠 마케팅 및 퍼포먼스 광고를 담당합니다.', '2022-05-20');

-- 2. binary_contents (프로필 이미지 3개 + 백업파일 1개)
-- INSERT INTO binary_contents (file_name, content_type, size, file_path) VALUES
--                                                                            ('profile_kim.png', 'image/png', 102450, '/uploads/profiles/2026/03/kim.png'),
--                                                                            ('profile_lee.jpg', 'image/jpeg', 204800, '/uploads/profiles/2026/03/lee.jpg'),
--                                                                            ('profile_park.png', 'image/png', 153600, '/uploads/profiles/2026/03/park.png'),
--                                                                            ('db_backup_20260313.zip', 'application/zip', 52428800, '/backups/db/20260313.zip');

-- 3. employees (직원 100명)
-- profile_image_id를 1~3 사이로 조정하거나 NULL로 설정하여 FK 오류 방지
INSERT INTO employees (employee_number, name, email, department_id, position, hire_date, status, profile_image_id) VALUES
                                                                                                                       ('EMP2018001', '강지훈', 'jihoon.kang@company.com', 1, '부장', '2018-03-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2018023', '조현우', 'hw.cho@company.com', 2, '시니어 개발자', '2018-05-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2019011', '윤서연', 'sy.yoon@company.com', 4, '팀장', '2019-01-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2019045', '임재희', 'jh.lim@company.com', 3, '시니어 디자이너', '2019-07-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2019088', '한상진', 'sj.han@company.com', 5, '과장', '2019-11-05', 'RESIGNED', NULL),
                                                                                                                       ('EMP2020002', '오민석', 'ms.oh@company.com', 2, '리드 개발자', '2020-02-14', 'ACTIVE', NULL),
                                                                                                                       ('EMP2020015', '서예진', 'yj.seo@company.com', 1, '차장', '2020-04-30', 'ACTIVE', NULL),
                                                                                                                       ('EMP2020033', '권도윤', 'dy.kwon@company.com', 4, '매니저', '2020-06-18', 'ON_LEAVE', NULL),
                                                                                                                       ('EMP2020067', '황보라', 'br.hwang@company.com', 3, '디자이너', '2020-09-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2020092', '송민준', 'mj.song@company.com', 5, '대리', '2020-12-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2021003', '전지민', 'jm.jeon@company.com', 2, '개발자', '2021-01-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2021028', '홍길동', 'gd.hong@company.com', 1, '대리', '2021-03-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2021041', '유나영', 'ny.yoo@company.com', 4, '사원', '2021-05-05', 'RESIGNED', NULL),
                                                                                                                       ('EMP2021066', '백승우', 'sw.baek@company.com', 5, '팀장', '2021-08-14', 'ACTIVE', NULL),
                                                                                                                       ('EMP2021089', '남궁민', 'min.nam@company.com', 2, '개발자', '2021-11-30', 'ACTIVE', NULL),
                                                                                                                       ('EMP2022005', '문지수', 'js.moon@company.com', 3, '주니어 디자이너', '2022-01-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2022022', '양현정', 'hj.yang@company.com', 4, '매니저', '2022-03-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2022047', '손동휘', 'dh.son@company.com', 2, '개발자', '2022-06-20', 'ON_LEAVE', NULL),
                                                                                                                       ('EMP2022071', '배수지', 'sj.bae@company.com', 1, '사원', '2022-09-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2022099', '고진욱', 'jw.ko@company.com', 5, '과장', '2022-12-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023001', '이철희', 'ch.lee@company.com', 2, '개발자', '2023-01-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023008', '김태리', 'tr.kim@company.com', 3, '디자이너', '2023-01-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023015', '박서준', 'sj.park@company.com', 4, '매니저', '2023-02-11', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023022', '최유정', 'yj.choi@company.com', 1, '대리', '2023-03-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023030', '정해인', 'hi.jung@company.com', 5, '사원', '2023-04-18', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023041', '유연석', 'ys.yoo@company.com', 2, '개발자', '2023-05-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023055', '한소희', 'sh.han@company.com', 3, '디자이너', '2023-06-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023062', '이동욱', 'dw.lee@company.com', 4, '사원', '2023-07-05', 'RESIGNED', NULL),
                                                                                                                       ('EMP2023078', '김세정', 'sj.kim2@company.com', 1, '사원', '2023-08-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023090', '박보영', 'by.park@company.com', 5, '대리', '2023-09-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2023101', '남주혁', 'jh.nam@company.com', 2, '개발자', '2023-11-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024002', '장기용', 'ky.jang@company.com', 3, '디자이너', '2024-01-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024015', '신세경', 'sk.shin@company.com', 4, '매니저', '2024-02-14', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024028', '이광수', 'ks.lee@company.com', 5, '주임', '2024-03-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024033', '송혜교', 'hk.song@company.com', 1, '과장', '2024-04-05', 'ON_LEAVE', NULL),
                                                                                                                       ('EMP2024045', '공유', 'yoo.gong@company.com', 2, '시니어 개발자', '2024-05-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024056', '김고은', 'ge.kim@company.com', 3, '디자이너', '2024-06-18', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024067', '조인성', 'is.cho@company.com', 4, '사원', '2024-07-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024078', '전지현', 'jh.jeon2@company.com', 5, '팀장', '2024-08-30', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024089', '현빈', 'bin.hyun@company.com', 1, '대리', '2024-09-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2024099', '손예진', 'yj.son@company.com', 2, '개발자', '2024-11-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025001', '강하늘', 'hn.kang@company.com', 3, '주니어 디자이너', '2025-01-02', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025012', '박신혜', 'sh.park2@company.com', 4, '사원', '2025-02-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025025', '이승기', 'sg.lee@company.com', 5, '사원', '2025-03-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025036', '수지', 'suzy@company.com', 1, '사원', '2025-04-20', 'RESIGNED', NULL),
                                                                                                                       ('EMP2025048', '임시완', 'sw.im@company.com', 2, '개발자', '2025-05-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025055', '윤아', 'yoona@company.com', 3, '디자이너', '2025-06-30', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025068', '박소담', 'sd.park@company.com', 4, '사원', '2025-08-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025079', '최우식', 'ws.choi@company.com', 5, '주임', '2025-09-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025088', '김다미', 'dm.kim@company.com', 2, '개발자', '2025-10-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2025095', '정경호', 'gh.jung@company.com', 1, '과장', '2025-11-22', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026001', '유재석', 'js.yoo@company.com', 4, '부장', '2026-01-02', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026005', '하하', 'haha@company.com', 5, '대리', '2026-01-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026010', '김종국', 'jk.kim@company.com', 2, '시니어 개발자', '2026-01-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026015', '지석진', 'sj.jee@company.com', 1, '차장', '2026-02-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026020', '송지효', 'jh.song2@company.com', 3, '팀장', '2026-02-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026025', '양세찬', 'sc.yang@company.com', 4, '대리', '2026-03-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026030', '전소민', 'sm.jeon@company.com', 5, '사원', '2026-03-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026035', '이효리', 'hr.lee@company.com', 1, '팀장', '2026-03-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026040', '이상순', 'ss.lee@company.com', 3, '시니어 디자이너', '2026-03-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026045', '비', 'rain@company.com', 4, '매니저', '2026-04-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026050', '김완선', 'ws.kim@company.com', 5, '과장', '2026-04-12', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026055', '엄정화', 'jh.uhm@company.com', 1, '부장', '2026-04-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026060', '제시', 'jessi@company.com', 2, '개발자', '2026-05-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026065', '화사', 'hwasa@company.com', 3, '디자이너', '2026-05-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026070', '성시경', 'sk.sung2@company.com', 4, '과장', '2026-05-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026075', '백종원', 'jw.baek@company.com', 5, '팀장', '2026-06-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026080', '이수근', 'sg.lee2@company.com', 1, '대리', '2026-06-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026085', '서장훈', 'jh.seo2@company.com', 2, '리드 개발자', '2026-07-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026090', '민경훈', 'kh.min@company.com', 3, '디자이너', '2026-07-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026095', '김희철', 'hc.kim@company.com', 4, '매니저', '2026-08-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026099', '강호동', 'hd.kang@company.com', 5, '본부장', '2026-08-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026101', '김준현', 'jh.kim3@company.com', 1, '사원', '2026-08-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026105', '문세윤', 'sy.moon@company.com', 2, '주니어 개발자', '2026-08-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026110', '유세윤', 'sy.yoo2@company.com', 3, '디자이너', '2026-09-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026115', '장도연', 'dy.jang@company.com', 4, '대리', '2026-09-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026120', '박나래', 'nr.park@company.com', 5, '사원', '2026-09-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026125', '양세형', 'sh.yang@company.com', 1, '사원', '2026-09-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026130', '이용진', 'yj.lee2@company.com', 2, '개발자', '2026-09-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026135', '이진호', 'jh.lee2@company.com', 3, '주니어 디자이너', '2026-09-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026140', '황제성', 'js.hwang@company.com', 4, '사원', '2026-10-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026145', '김용명', 'ym.kim@company.com', 5, '사원', '2026-10-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026150', '곽튜브', 'kwak@company.com', 2, '인턴', '2026-10-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026155', '빠니보틀', 'pani@company.com', 3, '인턴', '2026-10-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026160', '기안84', 'gian84@company.com', 3, '작가', '2026-10-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026165', '덱스', 'dex@company.com', 5, '사원', '2026-10-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026170', '침착맨', 'lee.mr@company.com', 2, '개발자', '2026-11-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026175', '주호민', 'pearl@company.com', 3, '디자이너', '2026-11-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026180', '이말년', 'malnyeon@company.com', 1, '과장', '2026-11-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026185', '조나단', 'nathan@company.com', 4, '사원', '2026-11-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026190', '파트리샤', 'trisha@company.com', 4, '사원', '2026-11-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026195', '코드쿤스트', 'cokun@company.com', 2, '개발자', '2026-11-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026200', '우도환', 'dh.woo@company.com', 5, '사원', '2026-12-01', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026205', '안은진', 'ej.ahn@company.com', 1, '사원', '2026-12-05', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026210', '남궁민2', 'min.nam2@company.com', 2, '팀장', '2026-12-10', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026215', '김선호', 'sh.kim3@company.com', 3, '디자이너', '2026-12-15', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026220', '임윤아', 'yoona.lim@company.com', 4, '매니저', '2026-12-20', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026225', '이준호', 'jh.lee3@company.com', 5, '사원', '2026-12-25', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026230', '최종인', 'last.choi@company.com', 1, '사원', '2026-12-30', 'ACTIVE', NULL),
                                                                                                                       ('EMP2026235', '이재명', 'jm.lee@company.com', 2, '사원', '2026-12-31', 'ACTIVE', NULL);

-- 4. employee_histories (변경 이력)
INSERT INTO employee_histories (type, employee_number, diff_json, memo, ip_address) VALUES
                                                                                        ('CREATED', 'EMP2020001', '[{"propertyName":"name","before":null,"after":"김철수"},{"propertyName":"department","before":null,"after":"경영지원팀"}]', '신규 입사 처리', '192.168.0.10'),
                                                                                        ('UPDATED', 'EMP2022033', '[{"propertyName":"status","before":"ACTIVE","after":"ON_LEAVE"}]', '개인 사정으로 인한 휴직', '192.168.0.15'),
                                                                                        ('CREATED', 'EMP2024012', '[{"propertyName":"name","before":null,"after":"정마케"},{"propertyName":"department","before":null,"after":"마케팅팀"}]', '신규 입사 처리', '127.0.0.1');

-- 5. backups (백업 이력)
INSERT INTO backups (worker, started_at, ended_at, status, file_id) VALUES
                                                                        ('system', '2026-03-12 02:00:00', '2026-03-12 02:05:00', 'COMPLETED', NULL),
                                                                        ('192.168.0.10', '2026-03-13 09:00:00', NULL, 'IN_PROGRESS', NULL),
                                                                        ('system', '2026-03-11 02:00:00', '2026-03-11 02:01:00', 'FAILED', NULL);